set(CPACK_GENERATOR "NSIS")
set(CPACK_COMPONENTS_ALL Unspecified)
set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VENDOR "Dongguan Jingwei Intelligent Technology")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "IO Testing Application")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME}")
set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${PROJECT_VERSION}-win64")
set(CPACK_PACKAGE_EXECUTABLES "${PROJECT_NAME}" "${PROJECT_NAME}")
set(CPACK_CREATE_DESKTOP_LINKS "${PROJECT_NAME}")
set(CPACK_NSIS_CREATE_ICONS_EXTRA "
  CreateShortCut \\\"$DESKTOP\\\\${PROJECT_NAME}.lnk\\\" \\\"$INSTDIR\\\\bin\\\\${PROJECT_NAME}.exe\\\"
")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
set(CPACK_NSIS_DISPLAY_NAME "${PROJECT_NAME} ${PROJECT_VERSION}")
set(CPACK_NSIS_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_NSIS_INSTALLED_ICON_NAME "${PROJECT_NAME}.exe")

find_program(_CPACK_NSIS_EXECUTABLE makensis
    HINTS "$ENV{ProgramFiles\(x86\)}/NSIS"
)
if(_CPACK_NSIS_EXECUTABLE)
    set(CPACK_NSIS_EXECUTABLE "${_CPACK_NSIS_EXECUTABLE}")
endif()
